In [1]:
# Librerías
from skimage import data
from skimage import io
from skimage.transform import resize
from skimage import color
from math import log

import matplotlib.pyplot as plt
import numpy as np

In [52]:
def LocalEntropy_fast(Im,n,x,y,bins):
    """
    Funcion que calcula la entropia local de una imagen
    Im = Imagen en escala de grises, n = tamaño de la celdilla 
    x,y = posicion X,Y del pixel a calcular
    """
    mlen = (n+2)*(n+2)
    
    # seleccionamos la matriz correspondiente
    localm = Im[(y-n):(y+n+1),(x-n):(x+n+1)] 
    hist, bin_edges = np.histogram(localm,bins) 
    print(hist)
    sump = 0
    for i  in hist:
        if (i!=0):
            pp = i/mlen
            sump += (pp)*np.log(pp) 
            
    return (-1*sump)

# --- Definimos la función del calculo de la entropia
def LocalEntropy(Im,n,x,y,bins,info):
    """
    Funcion que calcula la entropia local de una imagen
    Im = Imagen en escala de grises
    n = tamaño de la celdilla 
    x = posicion X del pixel a calcular
    Y = posicion Y del pixel a calcular
    info = 0 -> Devolvemos solo la entropía
    info = 1 -> Devolvemos mas información 
    """

    # seleccionamos la matriz correspondiente
    localm = Im[(y-n):(y+n+1),(x-n):(x+n+1)] 
    print(localm)
    size = (n+2)*(n+2)
    hist, bin_edges = np.histogram(localm,bins) #print(hist,bin_edges)
    print(hist)
    
    #Calculamos la entropía como suma de probabilidades por su logaritmo
    sump = 0
    for i  in hist:
        if (i!=0):
            print()
            print(i)
            pp = i/(size)   # probabilidad parcial
            lpp = np.log(pp) # log probabilidad parcial
            prod = pp*lpp # hacemos el producto
            sump += prod  # calculamos entropia
            print(pp)
            print(lpp)
    ent = -1*sump
    if (info==1):
        return ent,localm,hist,bin_edges
    else:
        return ent


    
    
def LocalEntropy_fast2(Im,n,x,y,bins):
    """
    Funcion que calcula la entropia local de una imagen
    Im = Imagen en escala de grises, n = tamaño de la celdilla 
    x,y = posicion X,Y del pixel a calcular
    """
    mlen = (n+2)*(n+2)
    
    # seleccionamos la matriz correspondiente
    localm = Im[(y-n):(y+n+1),(x-n):(x+n+1)] 
    t, bin_edges = np.histogram(localm,bins) 
    t = t[t != 0]
    t = t/mlen
    entr = -np.dot(t,np.log(t.T))
     
    return ent

In [53]:
im = np.array([[1,1,2,3,4,7],[1,1,2,2,2,9],[1,3,4,5,6,8],[1,3,4,2,3,7],[1,1,1,1,2,3]])
print(im)

[[1 1 2 3 4 7]
 [1 1 2 2 2 9]
 [1 3 4 5 6 8]
 [1 3 4 2 3 7]
 [1 1 1 1 2 3]]


In [54]:
n = 1
bins = 10
sh = im.shape
x = 2
y = 2

ent = LocalEntropy_fast2(im,n,x,y,bins)

print(ent)

1.5229550675313182


In [55]:
t = np.array([1 ,0 ,3 ,0 ,0 ,2 ,0 ,2 ,0 ,1])


print(entr)

1.5229550675313182


In [75]:

new = np.zeros((3,im.shape[0],im.shape[1]))

a = 0
for i in [1,4,6]:
    print(im)
    new[a,:,:] = im
    a+= 1

SyntaxError: invalid syntax (<ipython-input-75-98ad2ab8f396>, line 6)

In [73]:
new

array([[[1., 1., 2., 3., 4., 7.],
        [1., 1., 2., 2., 2., 9.],
        [1., 3., 4., 5., 6., 8.],
        [1., 3., 4., 2., 3., 7.],
        [1., 1., 1., 1., 2., 3.]],

       [[1., 1., 2., 3., 4., 7.],
        [1., 1., 2., 2., 2., 9.],
        [1., 3., 4., 5., 6., 8.],
        [1., 3., 4., 2., 3., 7.],
        [1., 1., 1., 1., 2., 3.]],

       [[1., 1., 2., 3., 4., 7.],
        [1., 1., 2., 2., 2., 9.],
        [1., 3., 4., 5., 6., 8.],
        [1., 3., 4., 2., 3., 7.],
        [1., 1., 1., 1., 2., 3.]]])

In [69]:
im

array([[1, 1, 2, 3, 4, 7],
       [1, 1, 2, 2, 2, 9],
       [1, 3, 4, 5, 6, 8],
       [1, 3, 4, 2, 3, 7],
       [1, 1, 1, 1, 2, 3]])